### PR TITLE
Update to runatlantis-0.8.3

### PR DESCRIPTION
**Pull request by Jaff**
Based on latest runatlantis/atlantis, includes your gh-teams-whitelist flag. I think I got all the diffs.

### CODE REVIEW

**Comment by Jaff** [comment]
@lkysow, @aknysh Review requested, please

**Comment by lkysow** [comment]
Hi Mark, I'm not sure what you're asking me to review?

**Comment by Jaff** [comment]
@lkysow This merges in updates in https://githhub.com/runatlantis/atlantis/ latest master, so you have the 0.8.3 updates.

**Comment by lkysow** [comment]
This is a fork of Atlantis that I don't manage 😁

**Comment by osterman** [comment]
@Jaff sorry for the delay here. We're updating it today to the latest release in https://github.com/cloudposse/atlantis/pull/30

**Pull request closed without merging**
